### ISSUE TITLE
Module buttons not fully clickable

### ISSUE THREAD

**Issue by Lehren** [FSG1/frontend#31]
There is an area in the module buttons that are not clickable.

Reproduction:
Go to the curriculum overview or the semester qualifications view.
Hover over an area of a module button that is not text, for instance below the text.
Try to click
Nothing happens

Expectation:
The entire button is clickable

**Comment by lukeelten** [comment]
Bug happens when one module is larger than the other modules. The inner div does not fill the height

**Comment by lukeelten** [comment]
Fixed with Pull Request #36
